# Generated by Django 3.0.6 on 2020-05-29 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorize', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='lid',
            field=models.CharField(default='na', max_length=100),
            preserve_default=False,
        ),
    ]
