# Generated by Django 3.0.6 on 2020-06-02 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorize', '0008_auto_20200602_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldvalues',
            name='verifiable',
        ),
        migrations.AddField(
            model_name='profilefields',
            name='verifiable',
            field=models.BooleanField(default=False),
        ),
    ]
